spring:
  application:
    name: hxgy-push-center
  rabbitmq:
    host: 10.88.67.114
    port: 5672
    username: jacklin
    password: jacklin
    publisher-confirms: true
    broadcast:
      exchange_name: broadExchange
  data:
    mongodb:
      uri: mongodb://10.88.32.127:27017/test

server:
  port: 8075
    
websocket:
  port: 8095
  
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://10.88.68.16:1111/eureka/
      
      
#线程池配置    
taskExecutePoolConf:
  threadPoolSize: 5 #线程池大小
  maxPoolSize: 10 #最大线程数
  queueCapacity: 50 #任务队列容量
  keepAliveSeconds: 60 #线程空闲时间
  threadNamePrefix: USER-SER #线程名称前缀


discover:
  heartBeatConf: #心跳参数设置
    MAX_UN_REC_PING_TIMES: 3 #定义客户端没有收到服务端的pong消息的最大次数
    MAX_UN_REC_PONG_TIMES: 3 #定义客户端没有收到服务端的pong消息的最大次数
    WRITE_WAIT_SECONDS: 20 #定义客户端多长时间未写请求后，发送心跳
    READ_WAIT_SECONDS: 21 #设置6秒检测chanel是否接受过心跳数据
    RE_CONN_WAIT_SECONDS: 3 #定义客户端多长时间重连
  localIp: 10.88.32.127
  localTcpPort: 8099
  nodes:
    - host: 10.88.67.3
      port: 8099
    - host: 10.88.69.120
      port: 8099
#discover:
#  localIp: 10.88.69.120
#  nodes:
#    - host: 10.88.67.3
#      port: 8099
#    - host: 10.88.32.127
#      port: 8099
